# Generated by Django 5.1 on 2024-08-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(default='en', max_length=10)),
                ('template_type', models.CharField(choices=[('text', 'Text'), ('media', 'Media')], max_length=10)),
                ('content_body', models.TextField()),
                ('media_type', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=10, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_action_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
