# Generated by Django 5.1 on 2024-08-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_collection', '0002_whatsapptemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='language',
            field=models.CharField(default='en_US', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='media_type',
            field=models.CharField(blank=True, choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='template_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('MEDIA', 'Media')], max_length=10),
        ),
    ]
