# Generated by Django 5.1 on 2024-09-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_collection', '0005_remove_contact_name_alter_contact_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=20, unique=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('new_contacts', models.PositiveIntegerField(default=0)),
                ('old_contacts', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
