# Generated by Django 5.1 on 2024-09-03 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_collection', '0006_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='upload',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='testing_collection.upload'),
            preserve_default=False,
        ),
    ]
