# Generated by Django 5.1 on 2024-09-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_collection', '0007_contact_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessagestatus',
            name='profile_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessagestatus',
            name='template_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessagestatus',
            name='wa_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessagestatus',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
