# Generated by Django 5.1 on 2024-09-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_collection', '0012_delete_messagetemplate_delete_whatsapptemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_message', models.CharField(max_length=10)),
                ('delivered_message', models.CharField(max_length=10)),
                ('read_message', models.CharField(max_length=10)),
            ],
        ),
    ]
